### PR TITLE
Update minimum node version to 10.15.3

### PR DESCRIPTION
**Pull request by cooldudezach**

### CODE REVIEW

**Comment by cooldudezach** [comment]
Considering that node 6.x went EOL yesterday, and node 10.x is the current Active LTS branch, it would be a good idea to update the minimum supported version.

**Comment by atla5** [comment]
i am getting some errors using `create-package`, however:
```
$ gulp create-package --view=VIEW_NAME
[12:59:04] Using gulpfile ~/path/to/gulpfile.js
[12:59:04] Starting 'create-package'...
[12:59:04] Starting 'select-view'...
[12:59:04] Finished 'select-view' after 9.63 ms
[12:59:04] Starting 'custom-js'...
[12:59:04] Starting 'select-view'...
[12:59:04] Finished 'select-view' after 343 μs
[12:59:04] Starting 'custom-html-templates'...
[12:59:04] Starting 'select-view'...
[12:59:04] Finished 'select-view' after 275 μs
[12:59:04] Starting '<anonymous>'...
[12:59:04] The following tasks did not complete: create-package, custom-js, custom-html-templates, <anonymous>
[12:59:04] Did you forget to signal async completion?
```

@cooldudezach: Are you getting a similar thing or are you familiar with the error?

**Comment by jswelker** [comment]
Actually I just did some more testing and found a few similar async issues in the watchers during `run`. I'm attaching all my updated task files.
[tasks.zip](https://github.com/ExLibrisGroup/primo-explore-devenv/files/3790618/tasks.zip)

**Comment by jswelker** [comment]
And just to keep the party going, here's another bug fix for gulp.config.js.

```
function getUseScss() {
	if(global.process.argv.includes('create-package')){
        return buildParams.useScss;
    }else{
        return useScss;
    }
}
```

**Comment by noamamit92** [comment]
complicated merge - tests should cover all , create package in risk

**Pull request merged**
