### PR TITLE
Custom html templates

### PR DESCRIPTION
**Pull request by mehmetc**
I do not like to include HTML files inside my JS files. 
With this pull-request I can save my files in the ```myView/html/templates``` directory. The files will be compiled into a ```customTemplates.js``` file. This ```$templateCache```  can be referenced with a  ```templateUrl``` from within your component

ex. ```myView/html/templates/myFile.html``` can be referenced using ```templateUrl: 'myFile.html' ``` 

```js
app.component('prmSomeComponentAfter', {
    bindings: {
        parentCtrl: '<'
    },
    templateUrl: 'myFile.html',
    controller: function() {
    // your code here
    }
  });
```

### CODE REVIEW

**Comment by gpeterso** [comment]
👍

**Comment by ajones3066** [comment]
+1

**Comment by muratseyhan** [comment]
:+1:  We've been storing the view name in a global variable just to work around this.

**Comment by thatbudakguy** [comment]
👍

**Pull request merged**
